### ISSUE TITLE
convert

### ISSUE THREAD

**Issue by name-svg** [ldubos/node-vlc-http#12]
Can I convert RTSP to HTTP? sorry,I am beginner

**Comment by ldubos** [comment]
Hi sorry for the delay, do you want to play a RTSP video stream on VLC w/ this package if it the case you just need to prefix the url with the right protocol when you ask to play a video like `rtsp://xxx.xxx.xxx.xxx`,

```javascript
vlc.addToQueueAndPlay('rtsp://xxx.xxx.xxx.xxx')
```
