### ISSUE TITLE
Error Event

### ISSUE THREAD

**Issue by oscardimanno** [ldubos/node-vlc-http#4]
Hi, i'm using this fantastic wrapper and i want to use the error event to determinate if VLC server is up or is down from receiving the rror conn refused through error.

```
vlc.on('error', listener: (err: Error) => {
  // do stuff
});
```

I'm using this code but doesn't work. I tried to know how to utilize by the library source but i'm yet a noob in NodeJS.
Can a gentle person can help me?
Thanks

**Comment by ldubos** [comment]
Hi @oscardimanno I just made a change to able you to handle this error from `.on('error', ...)` thanks for the report
