### ISSUE TITLE
Reconnect function

### ISSUE THREAD

**Issue by oscardimanno** [ldubos/node-vlc-http#6]
Implement a function that reconnect to the server after a timeout on a function that reconnect calling that.

I have seen that is existing if i connect to the server and it goes offline. But doesn't work if i start the script with the server offline.

**Comment by ldubos** [comment]
hi, you can now use:
```javascript
vlc.on('connect', () => {
  // do struff
})
```
to do things when vlc is connected

and you can define how many tries node-vlc-http will do before sending error and the interval between each tries

**Comment by oscardimanno** [comment]
How can I define that re-tries?

**Comment by ldubos** [comment]
```javascript
new VLC({
  // -1 for infinite retry
  maxTries: 10,
  // interval between each try in ms
  triesInterval: 500
})
```
