### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by mostfurious** [ldubos/node-vlc-http#7]

**Comment by s8sachin** [comment]
Hey @mostfurious , how did you solve this ?
I am also getting same issue.

**Comment by ldubos** [comment]
Hi @s8sachin I re-open the issue, I will investigate that tomorrow

**Comment by SNRSE** [comment]
any update I have the same error?

**Comment by undecidedapollo** [comment]
I was able to resolve the issue by setting the username to an empty string:
```
        const { VLC } = require('node-vlc-http');

        const vlc = new VLC({
            username: "",
            password: "password",
            maxTries: 1,
        });

        vlc.on('error', (err: Error) => {
            console.log(err);
        });

        vlc.on('connect', () => {
            console.log("connect");
            vlc.addToQueueAndPlay("https://content.jwplatform.com/manifests/yp34SRmf.m3u8");
        })
```

**Comment by ldubos** [comment]
hi here, I just updated the package to handle http errors and display better messages than ` Unexpected token < in JSON at position 0` in this case probably `401 Unauthorized` sorry for the late, I didn't had so much time to invest on the project :/
